# -*- coding:utf8 -*-
PC = "PC"
SUB_OP, XOR_OP, AND_OP, ADD_OP =  "SUB_OP", "XOR_OP", "AND_OP", "ADD_OP"
MINUS = "MINUS"

CMP_OP, CMPL_OP, CMPB_OP, TEST = "CMP_OP", "CMPL_OP", "CMPB_OP", "TEST"
JL, JG, JLE, JE, JMP, JMPQ = "JL", "JG", "JLE", "JE", "JMP", "JMPQ"
POP, POPQ, PUSH, PUSHQ, MOV, MOVL = "POP", "POPQ", "PUSH", "PUSHQ", "MOV", "MOVL"
CALLQ = "CALLQ"
HLT = "HLT"

NOPW, NOPL = "NOPW", "NOPL"
RETQ = 'RETQ'

ID = 'ID'
REGISTER = "REGISTER"

LPAREN, RPAREN = 'LPAREN', 'RPAREN'
LPOINTYBRACK, RPOINTYBRACK = "LPOINTYBRACK", "RPOINTYBRACK"
COMMA, COLON, PERCENT, DOLLAR = 'COMMA', "COLON", "PERCENT", "DOLLAR"
ASTERISK = "ASTERISK"

NUMBER = "NUMBER"

EOF = 'EOF'
