# -*- coding:utf8 -*-
PC = "PC"
SUB_OP, XOR_OP, AND_OP, ADD_OP, ADDL_OP, MUL_OP =  "SUB_OP", "XOR_OP", "AND_OP", "ADD_OP", "ADDL_OP", "MUL_OP"
LEA_OP = "LEA_OP"
NOT_OP, NEG_OP = "NOT_OP", "NEG_OP"
SHL_OP, SHR_OP = "SHL_OP" , "SHR_OP"
MINUS = "MINUS"

CMP_OP, CMPL_OP, CMPB_OP, TEST = "CMP_OP", "CMPL_OP", "CMPB_OP", "TEST"
JL, JG, JGE, JLE, JE, JNE, JMP, JMPQ = "JL", "JG", "JGE", "JLE", "JE", "JNE", "JMP", "JMPQ"
POP, POPQ, PUSH, PUSHQ, MOV, MOVL = "POP", "POPQ", "PUSH", "PUSHQ", "MOV", "MOVL"
CALLQ = "CALLQ"
HLT = "HLT"

NOP, NOPW, NOPL, XCHG = "NOP", "NOPW", "NOPL", "XCHG"
RETQ = 'RETQ'

ID = 'ID'
REGISTER = "REGISTER"

LPAREN, RPAREN = 'LPAREN', 'RPAREN'
LPOINTYBRACK, RPOINTYBRACK = "LPOINTYBRACK", "RPOINTYBRACK"
COMMA, COLON, PERCENT, DOLLAR = 'COMMA', "COLON", "PERCENT", "DOLLAR"
ASTERISK = "ASTERISK"

NUMBER = "NUMBER"

EOF = 'EOF'
